// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenuxServer.DbContexts;

#nullable disable

namespace RenuxServer.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RenuxServer.Models.ActiveChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("DegradedDatasetsJson")
                        .HasColumnType("text")
                        .HasColumnName("degraded_datasets_json");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("active_chats", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<int?>("AnswerVersion")
                        .HasColumnType("integer")
                        .HasColumnName("answer_version");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("FallbackReason")
                        .HasColumnType("text")
                        .HasColumnName("fallback_reason");

                    b.Property<bool?>("Grounded")
                        .HasColumnType("boolean")
                        .HasColumnName("grounded");

                    b.Property<double?>("GroundingScore")
                        .HasColumnType("double precision")
                        .HasColumnName("grounding_score");

                    b.Property<bool>("IsFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fallback");

                    b.Property<bool>("IsAsk")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ask");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<Guid?>("ParentQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_question_id");

                    b.Property<double?>("RelevanceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("relevance_score");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("RetrievalMode")
                        .HasColumnType("text")
                        .HasColumnName("retrieval_mode");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("text")
                        .HasColumnName("sources_json");

                    b.Property<string>("SuggestedQuestionsJson")
                        .HasColumnType("text")
                        .HasColumnName("suggested_questions_json");

                    b.Property<string>("VerificationStatus")
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VersionCreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_created_time");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ParentQuestionId")
                        .IsUnique()
                        .HasFilter("parent_question_id IS NOT NULL AND is_ask = FALSE AND is_current = TRUE");

                    b.HasIndex("ParentQuestionId", "AnswerVersion")
                        .IsUnique()
                        .HasFilter("parent_question_id IS NOT NULL AND answer_version IS NOT NULL AND is_ask = FALSE");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasFilter("request_id IS NOT NULL");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.CouncilSignupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<DateTime?>("ReviewedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("council_signup_requests", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("in_app")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<string>("RemindDaysBefore")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("7,1,0")
                        .HasColumnName("remind_days_before");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Topic")
                        .IsUnique();

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.GuestChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("guest", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Majorname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major_name");

                    b.HasKey("Id");

                    b.HasIndex("Majorname")
                        .IsUnique();

                    b.ToTable("majors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("293e8c9e-5c1d-40d7-adf4-3df7a419e4d6"),
                            Majorname = "통계학과"
                        },
                        new
                        {
                            Id = new Guid("f762ae12-21f7-4943-a78d-ab3931506306"),
                            Majorname = "수학과"
                        });
                });

            modelBuilder.Entity("RenuxServer.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("MajorId")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.ProductEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("answer_key");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("exclusion_reason");

                    b.Property<bool?>("Grounded")
                        .HasColumnType("boolean")
                        .HasColumnName("grounded");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_excluded");

                    b.Property<bool?>("IsFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fallback");

                    b.Property<DateTime>("OccurredTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_time");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SessionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_key");

                    b.Property<int?>("SourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_count");

                    b.Property<string>("SubjectKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_key");

                    b.Property<int?>("SuggestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("suggestion_count");

                    b.Property<int?>("SuggestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("suggestion_index");

                    b.HasKey("Id");

                    b.HasIndex("AnswerKey", "EventType");

                    b.HasIndex("EventType", "OccurredTime");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SubjectKey", "OccurredTime");

                    b.ToTable("product_events", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("Rolename")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c22bc8f7-98b8-45a3-9053-3b779e027649"),
                            Rolename = "학생회"
                        },
                        new
                        {
                            Id = new Guid("ec62f7d6-069d-4a47-8801-db61b938a299"),
                            Rolename = "관리자"
                        },
                        new
                        {
                            Id = new Guid("b4114fd1-c9f0-4171-821f-b53a15faba9b"),
                            Rolename = "일반학생"
                        },
                        new
                        {
                            Id = new Guid("7a3f2c44-9d1e-4b6a-8f25-6c0e9b51d7a2"),
                            Rolename = "총학생회"
                        });
                });

            modelBuilder.Entity("RenuxServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_time");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_date");

                    b.Property<int>("ReminderDaysBefore")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_days_before");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("TargetDate");

                    b.HasIndex("UserId");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.ActiveChat", b =>
                {
                    b.HasOne("RenuxServer.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuxServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RenuxServer.Models.ChatMessage", b =>
                {
                    b.HasOne("RenuxServer.Models.ActiveChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuxServer.Models.ChatMessage", "ParentQuestion")
                        .WithMany()
                        .HasForeignKey("ParentQuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chat");

                    b.Navigation("ParentQuestion");
                });

            modelBuilder.Entity("RenuxServer.Models.CouncilSignupRequest", b =>
                {
                    b.HasOne("RenuxServer.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("RenuxServer.Models.GuestChat", b =>
                {
                    b.HasOne("RenuxServer.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("RenuxServer.Models.Organization", b =>
                {
                    b.HasOne("RenuxServer.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("RenuxServer.Models.NotificationPreference", b =>
                {
                    b.HasOne("RenuxServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RenuxServer.Models.User", b =>
                {
                    b.HasOne("RenuxServer.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuxServer.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RenuxServer.Models.UserNotification", b =>
                {
                    b.HasOne("RenuxServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
