// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenuxServer.DbContexts;

#nullable disable

namespace RenuxServer.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RenuxServer.Models.ActiveChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("created_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("active_chats", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("created_time");

                    b.Property<bool>("IsAsk")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ask");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedTime");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.GuestChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("created_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("guest", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Majorname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major_name");

                    b.HasKey("Id");

                    b.HasIndex("Majorname")
                        .IsUnique();

                    b.ToTable("majors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("293e8c9e-5c1d-40d7-adf4-3df7a419e4d6"),
                            Majorname = "통계학과"
                        },
                        new
                        {
                            Id = new Guid("f762ae12-21f7-4943-a78d-ab3931506306"),
                            Majorname = "수학과"
                        });
                });

            modelBuilder.Entity("RenuxServer.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("created_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<long>("UpdatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_time");

                    b.HasKey("Id");

                    b.HasIndex("MajorId")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("Rolename")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c22bc8f7-98b8-45a3-9053-3b779e027649"),
                            Rolename = "학생회"
                        },
                        new
                        {
                            Id = new Guid("ec62f7d6-069d-4a47-8801-db61b938a299"),
                            Rolename = "교직원"
                        },
                        new
                        {
                            Id = new Guid("b4114fd1-c9f0-4171-821f-b53a15faba9b"),
                            Rolename = "일반학생"
                        });
                });

            modelBuilder.Entity("RenuxServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("created_time");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role");

                    b.Property<long>("UpdatedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RenuxServer.Models.ActiveChat", b =>
                {
                    b.HasOne("RenuxServer.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuxServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RenuxServer.Models.ChatMessage", b =>
                {
                    b.HasOne("RenuxServer.Models.ActiveChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("RenuxServer.Models.GuestChat", b =>
                {
                    b.HasOne("RenuxServer.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("RenuxServer.Models.Organization", b =>
                {
                    b.HasOne("RenuxServer.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("RenuxServer.Models.User", b =>
                {
                    b.HasOne("RenuxServer.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuxServer.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
