# fly.toml app configuration file generated for rag-cinder-harborbird-7558 on 2026-05-12T14:19:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rag-cinder-harborbird-7558'
primary_region = 'nrt'

[build]

[env]
  HF_HOME = "/app/artifacts/huggingface_cache"
  HUGGINGFACE_HUB_CACHE = "/app/artifacts/huggingface_cache"
  SENTENCE_TRANSFORMERS_HOME = "/app/artifacts/huggingface_cache"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[[mounts]]
  source = "rag_data"
  destination = "/app/artifacts"
